### ISSUE TITLE
Document missing Python 3 compatibility

### ISSUE THREAD

**Issue by febsn** [Blueshoe/djangocms-layouter#19]
I just realized that this plugin isn't Python3 compatible:

`Exception Value: name 'unicode' is not defined
Exception Location: /Users/fabian/.virtualenvs/petaw/src/layouter/layouter/models.py in __str__, line 77`

I kindly ask you to document that in the readme. If I at some point find time to create a Python 3 compatible version, I'll happily create a pull request.

**Comment by SteinRobert** [comment]
Thank you very much. Indeed we haven't tested the plugin on Python3 yet. I added a hint and a todo to the readme.
I also opened a new branch, which already contains a few code changes for the Python3 compatibility. It's not tested yet but feel free to have a look at it:
https://github.com/Blueshoe/djangocms-layouter/tree/python_3_compatibility

**Comment by SteinRobert** [comment]
The project is now Python3 compatible. Thank you very much for bringing that issue to our attention.

**Comment by febsn** [comment]
Thanks a lot :)
